name: 'Build and Push Docker Image'
on:
  repository_dispatch:
  schedule:
    interval: 'weekly'

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - id: mhsendmail
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          owner: mailhog
          repo: mhsendmail
          excludes: prerelease, draft
      - id: self
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: ${{ github.repository }}

  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ jobs.check-release.steps.mhsendmail.outputs.release }} != ${{ jobs.check-release.steps.self.outputs.release }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: latest, ${{ jobs.check-release.steps.mhsendmail.outputs.release }}
          build_args: MHSENDMAIL_VERSION=${{ jobs.check-release.steps.mhsendmail.outputs.release }}
